### ISSUE TITLE
Reset Build Number

### ISSUE THREAD

**Issue by PradeepChireddyTR** [einaregilsson/build-number#11]
How to reset the build numbers on monthly basis.

**Comment by einaregilsson** [comment]
You could remote the build-number-X tag and make a new one yourself, e.g. build-number-50 if you want 50 as the starting point.

**Comment by rvalentini** [comment]
You could set up a cron job to trigger this little bash script. It expects the new starting point as argument
```bash
#!/bin/bash
if [ -z "$1" ]
  then
    echo "To reset the build-number please specify a new start number"
  else
    echo "Setting build number to $1 ..."

    #remove the old build-number tag remote & local
    git fetch --tags
    git push -d origin $(git tag -l "build-number-*")
    git tag -d $(git tag -l "build-number-*")

    #set new build-number
    git tag build-number-$1
    git push origin build-number-$1

    echo "DONE"
fi
```

**Comment by PradeepChireddyTR** [comment]
> You could remote the build-number-X tag and make a new one yourself, e.g. build-number-50 if you want 50 as the starting point.

My build number is running at 150 now.

- name: Generate build number
      id: buildnumber-0
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}} 

How to reset the build to 1?

**Comment by einaregilsson** [comment]
@PradeepChireddyTR  You can't do it in the YAML file, you can only do it by changing the tag `build-number-x`.
