### ISSUE TITLE
Build number write into file

### ISSUE THREAD

**Issue by PenzinAlexander** [einaregilsson/build-number#12]
Hello. Thank you for your work and this script. 
But how can i use this variable? I mean i want to put this build.version into file? 

Thank you.

**Comment by einaregilsson** [comment]
Hi. I no longer reccommend using this action, you can now just use the environment variable `$GITHUB_RUN_NUMBER` instead, which GitHub provides. To put into a file you just write a script that writes it to a file, that's not part of the action.
