### ISSUE TITLE
`set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by sanjivpurohit** [einaregilsson/build-number#13]
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by einaregilsson** [comment]
Thanks for letting me know :) I'll try to get it fixed soon, although this action should really not be used, much easier to just use $GITHUB_RUN_NUMBER now.

**Comment by lukemcgregor** [comment]
Yeah except run_number resets when you rename an action, and you cant propagate it between actions.

**Comment by lukemcgregor** [comment]
fixed by #14

**Comment by lukemcgregor** [comment]
@einaregilsson GITHUB_RUN_NUMBER doesn't work between different workflows (for example I have a different one for production), It also resets if you change the workflow name. GITHUB_RUN_ID does technically work, but it makes the ugliest version number possible (I think its a global run inside GitHub).

This action seems like a good compromise and give some control over the number

**Comment by einaregilsson** [comment]
Fair point. I've published v3 which uses the updated way of setting env variables.

**Comment by lukemcgregor** [comment]
Cool thanks 👍
