### ISSUE TITLE
Old build-number-x tags re-appear

### ISSUE THREAD

**Issue by mherbrich** [einaregilsson/build-number#15]
Hi,
since couple of months (maybe since I upgraded to V3?) I have the following issue:
The script fails, because there are too many "build-number-xxx" tags.
Then I delete all tags, but the latest. I re-run GitHub actions and everything works fine.
But somehow after sometimes all old "build-number-xxx" tags re-appear and the script fails again.
Any idea what is the problem and from were the old tags are re-created?

**Comment by einaregilsson** [comment]
Sorry, don't know why that happens. Can you check the logs of the last few runs, does it say anything about deleting old tags?

**Comment by y-ohno-p** [comment]
I am getting the same error.
>Error: ERROR: Too many my-build-number- refs in repository, found 7, expected only 1. Check your tags!

I check out the repository, modify the source code, and push it.
Then multiple tags are present and an error occurs.

Do I have to delete the old tags locally before pushing?

**Comment by einaregilsson** [comment]
Not sure why that is happening. I just know that I made the script abort the deleting if it found lots of tags because if everything is working properly there should be only one, and when you see unexpected state it's usually not the best course of action to delete everything you see :)

Are you pushing all your local tags to the remote repo or something like that? I'm wondering whether something like that could be causing this.

**Comment by y-ohno-p** [comment]
Problem solved.

I am using Sourcetree as my git client.
The "Push all tags to remotes" setting was turned on.

Thank you for your advice.
![image](https://user-images.githubusercontent.com/65893103/108052253-34004800-708f-11eb-987f-fe7bfa4a74e8.png)

**Comment by einaregilsson** [comment]
Ah, that makes sense. Thanks for letting me know.

**Comment by Zyther** [comment]
I am finding similar cases of this issue in my repositories when Visual Studio is used as the primary git client

**Comment by einaregilsson** [comment]
@Zyther Ok, is there an option there to not push all tags to remotes?

**Comment by Zyther** [comment]
Thanks all, resolved on my end

**Comment by mitkokostakev** [comment]
Hi guys,
so the solution is to remove all tags? Is there another way to solve this issue in case we need to keep the tags in git repo?

**Comment by einaregilsson** [comment]
@mitkokostakev really the best solution is to stop using this action and use the $GITHUB_RUN_NUMBER environment variable for build numbers (+ add some offset to it if you need to maintain an old build number).
