### ISSUE TITLE
Set up initial build number through inputs

### ISSUE THREAD

**Issue by HavenDV** [einaregilsson/build-number#16]
I need the default build number to start at 0, not 1. I think it's worth adding a separate input for this. I can prepare a PR if needed.
In addition, it will also simplify the Use case with a start number.

**Comment by einaregilsson** [comment]
Hi. It's probably best for you to just fork this repo and use your own copy. I don't really have any plans to add more to this action, since for most people it's easily replaced by just using the `$GITHUB_RUN_NUMBER` environment variable that GitHub Actions has now.

**Comment by HavenDV** [comment]
I got it, thanks for the quick reply
