### ISSUE TITLE
Getting the current build number without generating a new one via the input parameter

### ISSUE THREAD

**Issue by HavenDV** [einaregilsson/build-number#17]
I need the ability to get build number without generating a new one.
Cause:
I am trying to create an auto versioning system based on [Conventional Commits](https://www.conventionalcommits.org/) and your generator. Each `breaking change` commit will create a new `Major` version, each `feat:` commit will create a new `Minor` version and each `fix:` will create a `Build` version, where the final version will look like `Major.Minor.Build`.

**Comment by einaregilsson** [comment]
Hi. It's probably best for you to just fork this repo and use your own copy. I don't really have any plans to add more to this action, since for most people it's easily replaced by just using the `$GITHUB_RUN_NUMBER` environment variable that GitHub Actions has now.

**Comment by HavenDV** [comment]
I got it, thanks for the quick reply
