### ISSUE TITLE
Replace deprecated set-output command

### ISSUE THREAD

**Issue by lnhrdt** [einaregilsson/build-number#21]
When using this action, GitHub Actions displays the following warning:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Can this action be updated to prevent any issues when the `set-output` command is disabled?

**Comment by gzur** [comment]
This repo is being archived due to the maintainer passing away and development has moved to https://github.com/onyxmueller/build-tag-number

Consider re-creating this issue there (if it hasn't been fixed there already)
