### ISSUE TITLE
Update to run on Node 16 instead of Node 12

### ISSUE THREAD

**Issue by lnhrdt** [einaregilsson/build-number#22]
When using this action, GitHub Actions displays the following warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: einaregilsson/build-number@v3

Can this action be updated to Node 16 to prevent any possible issues when the change to Node 16 is forced?

**Comment by gzur** [comment]
This repo is being archived due to the maintainer passing away and development has moved to https://github.com/onyxmueller/build-tag-number

Consider re-creating this issue there (if it hasn't been fixed there already)
