### ISSUE TITLE
hardcoded `build-number` prefix isn't very flexible

### ISSUE THREAD

**Issue by james-mckenzie-cko** [einaregilsson/build-number#6]
We're considering using your action (great work, btw), but it would be useful if the `build-number` prefix wasn't hardcoded. Appreciate that you can add another prefix, but two seems unnecessary. We could either remove the `build-number` string altogether, or have the custom prefix override the `build-number` string? What are your thoughts?

**Comment by einaregilsson** [comment]
Not sure I understand the use case. Why is naming the tag build-number problematic for you?

**Comment by einaregilsson** [comment]
No response on this so I'm closing it. The prefix should be enough.
