### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by npross** [einaregilsson/build-number#9]
If two builds run at the same time they both can get the same build number. I've had this happen a few times.

**Comment by einaregilsson** [comment]
Ok, not sure how I could prevent that. Are the two builds being triggered by the same commit?

**Comment by npross** [comment]
Yes, but no big deal I've switched to using the number of commits as the build number.

**Comment by einaregilsson** [comment]
Sounds like a good workaround. Closing this, since I don't think we have a viable way to fix this.
